### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by 5um1th** [claudiajs/example-projects#12]
using npm@2.14.12
using node@v4.2.6

I was testing out web-api-test project after i do "npm install" and then follow it by "npm start"
which runs "claudia create --name web-api-test --region us-east-1 --api-module web" it results in an error.

`> claudia create --name web-api-test --region us-east-1 --api-module web

packaging files	npm pack /Users/<HOME>/Code/Bots/SMSBotApi
npm pack /Users/<HOME>/Code/Bots/SMSBotApi failed. Check /var/folders/ls/fhnr088j0dbgw3p7zrk7g5c80000gq/T/798a05c1-fc09-47e5-852d-290f2e166000

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! web-api-test@ start: `claudia create --name web-api-test --region us-east-1 --api-module web`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-api-test@ start script 'claudia create --name web-api-test --region us-east-1 --api-module web'.
npm ERR! This is most likely a problem with the web-api-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     claudia create --name web-api-test --region us-east-1 --api-module web
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-api-test
npm ERR! There is likely additional logging output above.`

This is working fine with previous versions of claudia (2.0.0) and claudia api builder (2.0.0) but not with  claudia api builder 2.0.2 and claudia 2.1.2

Do I have to upgrade nodejs and npm? are there any minimum requirements?

**Comment by stojanovic** [comment]
Version was missing in package.json file, it should work now.

Node 4.2.6 should work fine, I am using 4.3.2 because that's the version on AWS Lambda.
