### ISSUE TITLE
Alexa example which url?

### ISSUE THREAD

**Issue by kirkins** [claudiajs/example-projects#17]
When I run 

    npm run create

I get back something like this:
```

{
  "lambda": {
    "role": "alexa-spell2-executor",
    "name": "alexa-spell2",
    "region": "us-east-1"
  },
  "api": {
    "id": "xyxyxy",
    "module": "bot",
    "url": "https://xyxyxy.execute-api.us-east-1.amazonaws.com/latest",
    "deploy": {
      "alexa": "https://xyxyxy.execute-api.us-east-1.amazonaws.com/latest/alexa"
    }
  }
}

```

Which url should I be using `https://xyxyxy.execute-api.us-east-1.amazonaws.com/latest/alexa`?

I try both and get back:

> The remote endpoint could not be called, or the response it returned was invalid.

![screenshot_2017-02-16_16-01-11](https://cloud.githubusercontent.com/assets/9503662/23040930/3732a5f8-f461-11e6-8629-427a1a8826ac.png)

**Comment by gojko** [comment]
please use the gitter chat for questions
