### ISSUE TITLE
How to serve jade/pug template?

### ISSUE THREAD

**Issue by malikimprowised** [claudiajs/example-projects#27]
Use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead to ask a general question or request assistance/support.

Please use GitHub issues only to report bugs with example projects. To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour:

* What actually happens:

* Link to a minimal, executable project that demonstrates the problem:

* Steps to install the project:

* Steps to reproduce the problem:

**Comment by gojko** [comment]
Use the Claudia.js Gitter Chat instead to ask a general question or request assistance/support.
