### ISSUE TITLE
Pass custom headers through Amazon API Gateway

### ISSUE THREAD

**Issue by sebastienfi** [claudiajs/example-projects#37]
Hi Team!

How to pass custom headers through Amazon API Gateway with ClaudiaJS?

A POST route built with `ApiBuilder`  does not receive natively the custom headers. 
An external provider realizes a POST every minute to an endpoint of our API Gateway. This provider offers important information only as POST Headers. These information changes at every POST. I need to access these custom headers values in the Lambda... 

It's about configuring the Request Headers, not the [Response headers](https://github.com/claudiajs/claudia-api-builder/blob/master/docs/customise-responses.md) ;)

Any help much appreciated...

**Comment by sebastienfi** [comment]
@gojko Why closing my question? I don't have my answer :) I'm also sure this would help others.

**Comment by gojko** [comment]
we use github issues only for bugs, questions should go to the gitter chat channel. you already posted the question there so I thought that it's not important to explain the channel link here again
