### ISSUE TITLE
Repo-label example project badge is not rendering in the README

### ISSUE THREAD

**Issue by Winter-Guerra** [claudiajs/example-projects#5]
Probably because `repolabels.net` currently does not output `Access-Control-Allow-Origin: *` in the svg response headers. Since GitHub now proxies all image traffic through `camo.githubusercontent.com`, some CORS access control (such as the line above) is going to be necessary for allowing SVGs to render in READMEs.

**Comment by Winter-Guerra** [comment]
![screen shot 2016-05-05 at 11 25 29 pm](https://cloud.githubusercontent.com/assets/241838/15063498/b48be8b4-1318-11e6-8d58-992355ba298b.jpg)

**Comment by gojko** [comment]
this seems to be a recurring problem with github image caching. cors works well on repolabels.net, and in any case, cors is only important for browser cross-origin access, not for server-side proxying.
