### ISSUE TITLE
How to run web-api project locally?

### ISSUE THREAD

**Issue by ghost** [claudiajs/example-projects#9]
I was testing the web-api project example and I was able to deployed into AWS API Gateway/ Lambda successfully.

Anyway, I was wondering if there is any way to run this example locally?

Thanks in advance

**Comment by gojko** [comment]
please don't use github issues for general questions, there's a gitter channel for that: https://gitter.im/claudiajs/claudia

**Comment by thebarty** [comment]
@gojko Just letting you know: I really think that you should allow questions on github. Most projects I know do that. The end result will be that each useCase/question and the corresponding answers will be much better documented (than in random gitter-chat). In total there will be less support work for you and fellow contributors.
